"""initial schema

Revision ID: c85d39a8c0b6
Revises: 
Create Date: 2026-03-09 11:58:21.284767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c85d39a8c0b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('exam_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exam_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cargo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exam_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('booklet_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expected_questions', sa.Integer(), nullable=False),
    sa.Column('partial', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('exam_id')
    )
    op.create_table('answer_keys',
    sa.Column('answer_key_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exam_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
    sa.PrimaryKeyConstraint('answer_key_id'),
    sa.UniqueConstraint('exam_id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('statement', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('result_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exam_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('wrong', sa.Integer(), nullable=False),
    sa.Column('blank', sa.Integer(), nullable=False),
    sa.Column('annulled', sa.Integer(), nullable=False),
    sa.Column('pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('answer_key_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_key_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['answer_key_id'], ['answer_keys.answer_key_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result_breakdown',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('candidate_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('correct_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hit', sa.Boolean(), nullable=False),
    sa.Column('annulled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['results.result_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result_breakdown')
    op.drop_table('answer_key_items')
    op.drop_table('results')
    op.drop_table('questions')
    op.drop_table('answer_keys')
    op.drop_table('exams')
    # ### end Alembic commands ###
